name: Leslie Bordonné
title: bordonne.com
description: Personal website and blog
url: http://bordonne.com/

theme: jekyll-theme-cayman
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
